name = "animanga-site"
compatibility_date = "2026-05-15"
main = "./dist/_worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
API_URL = "https://animanga-api.ionicerrrrscode.workers.dev"

[[services]]
binding = "API"
service = "animanga-api"
